layout: manewry
permalink: /manewry/

layout: chess
permalink: /chess/

layout: deadpxlz
permalink: /deadpxlz/

theme: jekyll-theme-midnight
title: Maciej Pawłowski
description: That's site about me and my projects
